import type { Metadata } from "next";
import { notFound } from "next/navigation";

import commercialHero from "../../../Selected-Pictures-for-Website/Services Pages/Commercial HVAC Service & Maintenance/01-commercial-hvac-main.webp";
import commercialSecondary from "../../../Selected-Pictures-for-Website/Services Pages/Commercial HVAC Service & Maintenance/02-commercial-hvac-secondary.webp";
import miniSplitHero from "../../../Selected-Pictures-for-Website/Services Pages/Ductless Mini-Split Install & Service/01-mini-split-service-main.jpg";
import miniSplitSecondary from "../../../Selected-Pictures-for-Website/Services Pages/Ductless Mini-Split Install & Service/02-mini-split-service-secondary.jpg";
import furnaceHero from "../../../Selected-Pictures-for-Website/Services Pages/Furnace Service & Repair/01-furnace-service-main.webp";
import furnaceSecondary from "../../../Selected-Pictures-for-Website/Services Pages/Furnace Service & Repair/02-furnace-service-secondary.jpg";
import heatPumpHero from "../../../Selected-Pictures-for-Website/Services Pages/Heat Pump Service & Repair/01-heat-pump-service-main.webp";
import heatPumpSecondary from "../../../Selected-Pictures-for-Website/Services Pages/Heat Pump Service & Repair/02-heat-pump-service-secondary.jpg";
import componentHero from "../../../Selected-Pictures-for-Website/Services Pages/HVAC Component Repair & Replacement/01-hvac-component-repair-main.jpg";
import componentSecondary from "../../../Selected-Pictures-for-Website/Services Pages/HVAC Component Repair & Replacement/02-hvac-component-repair-secondary.jpg";
import maintenanceHero from "../../../Selected-Pictures-for-Website/Services Pages/HVAC Maintenance & Tune-Ups/01-hvac-maintenance-main.jpg";
import maintenanceSecondary from "../../../Selected-Pictures-for-Website/Services Pages/HVAC Maintenance & Tune-Ups/02-hvac-maintenance-secondary.jpg";
import replacementHero from "../../../Selected-Pictures-for-Website/Services Pages/HVAC Replacement & Changeouts/01-hvac-replacement-main.jpg";
import replacementSecondary from "../../../Selected-Pictures-for-Website/Services Pages/HVAC Replacement & Changeouts/02-hvac-replacement-secondary.jpg";
import airQualityHero from "../../../Selected-Pictures-for-Website/Services Pages/Indoor Air Quality/01-indoor-air-quality-main.jpg";
import airQualitySecondary from "../../../Selected-Pictures-for-Website/Services Pages/Indoor Air Quality/02-indoor-air-quality-secondary.jpg";
import thermostatHero from "../../../Selected-Pictures-for-Website/Services Pages/Thermostat Replacement & Installation/01-thermostat-installation-main.jpg";
import thermostatSecondary from "../../../Selected-Pictures-for-Website/Services Pages/Thermostat Replacement & Installation/02-thermostat-installation-secondary.jpg";
import { ServiceDetailPage, type ServiceDetailContent } from "@/components/service-detail-page";
import { createPageMetadata } from "@/lib/seo";

type ServicePageDefinition = {
  title: string;
  description: string;
  content: ServiceDetailContent;
};

const serviceAreaDescription = "Ferguson & Sons is based in Chesapeake and provides regular HVAC service throughout Chesapeake, Virginia Beach, Norfolk, Portsmouth, eastern Suffolk, and surrounding communities within its regular South Hampton Roads coverage area.";

const servicePages: Record<string, ServicePageDefinition> = {
  "hvac-maintenance": {
    title: "HVAC Maintenance & Tune-Ups | Ferguson & Sons",
    description: "HVAC tune-ups, preventative maintenance, cleaning, and seasonal service across Chesapeake and South Hampton Roads.",
    content: {
      eyebrow: "HVAC Maintenance / Tune-Ups / Cleaning",
      title: <><strong>Keep Your HVAC System</strong><span>Ready With Routine Care.</span></>,
      lead: "Regular HVAC maintenance gives you a practical way to check system condition, address cleaning needs, and catch potential problems earlier. Ferguson & Sons provides hands-on tune-ups and preventative service for residential and commercial systems.",
      heroImage: maintenanceHero,
      heroAlt: "Ferguson & Sons technician cleaning a residential outdoor HVAC unit",
      imageBadgeEyebrow: "Preventative Care",
      imageBadge: "Check It Before It Breaks",
      problemsHeading: <>When Your System Needs <em>Professional Attention</em></>,
      problemsIntro: "Routine service can address maintenance needs before they become larger comfort or reliability problems.",
      problems: [
        { label: "Seasonal Tune-Up Due", icon: "clock" },
        { label: "Outdoor Equipment Needs Cleaning", icon: "airflow" },
        { label: "Coil or Condenser Buildup", icon: "gear" },
        { label: "Filter or Airflow Concerns", icon: "air-quality" },
        { label: "Changes in System Performance", icon: "gauge" },
        { label: "Potential Issues to Check Early", icon: "diagnosis" },
      ],
      approachTitle: <>Inspect, Clean, and Service.<span>Explain What We Find.</span></>,
      approachIntro: "Maintenance should be clear and useful. We inspect relevant system areas, complete appropriate cleaning and service, and explain any condition that may need attention.",
      approachCta: "Schedule Maintenance",
      steps: [
        { title: "Inspect the System", description: "We review system condition, airflow-related maintenance needs, and the equipment areas relevant to the visit.", icon: "diagnosis" },
        { title: "Clean & Maintain", description: "We complete appropriate tune-up and cleaning work, including condenser or coil care where needed.", icon: "tools" },
        { title: "Review the Findings", description: "We explain the completed service and point out any potential problem that may deserve further attention.", icon: "family" },
      ],
      realServiceEyebrow: "Real Preventative Service",
      realServiceTitle: <>Routine Care Starts With<br />Seeing the System Up Close</>,
      realServiceDescription: "Ferguson & Sons uses hands-on inspection and cleaning to support reliable system operation. The goal is practical preventative care, not a sales pitch for replacement.",
      realServicePoints: ["Seasonal Tune-Ups", "Professional HVAC Cleaning", "Residential & Commercial Maintenance"],
      realServiceImage: maintenanceSecondary,
      realServiceAlt: "Ferguson & Sons technician cleaning an outdoor HVAC condenser during maintenance",
      supportEyebrow: "HVAC Maintenance Plan",
      supportTitle: "Prefer a Simple Year-Round Maintenance Option?",
      supportDescription: "The Ferguson & Sons HVAC Maintenance Plan is $299 per year per system, approximately $25 per month, and includes two professional maintenance visits per year.",
      supportItems: [
        { label: "$299 Per Year, Per System", icon: "clock" },
        { label: "Approximately $25 Per Month", icon: "gauge" },
        { label: "2 Professional Visits Per Year", icon: "tools" },
        { label: "Preventative-Care Focus", icon: "shield" },
      ],
      relatedServices: [
        { title: "HVAC Maintenance Plan", description: "A simple option for two professional maintenance visits each year.", href: "/maintenance-plan/", icon: "clock" },
        { title: "A/C Repair & Diagnosis", description: "Troubleshooting and repair when your cooling system is not performing properly.", href: "/services/ac-repair/", icon: "snowflake" },
        { title: "Heat Pump Service / Repair", description: "Diagnosis, service, repair, and maintenance for heat pump systems.", href: "/services/heat-pump-repair/", icon: "heat-pump" },
        { title: "Furnace Service / Repair", description: "Straightforward furnace diagnostics, service, repair, and maintenance.", href: "/services/furnace-repair/", icon: "furnace" },
      ],
      serviceAreaEyebrow: "Local HVAC Maintenance",
      serviceAreaTitle: "Serving South Hampton Roads",
      serviceAreaDescription,
      finalCtaHeading: "Ready to Schedule HVAC Maintenance?",
      finalCtaDescription: "Practical tune-ups, cleaning, and preventative HVAC service from a local Chesapeake team.",
    },
  },
  "commercial-hvac": {
    title: "Commercial HVAC Service & Maintenance | Ferguson & Sons",
    description: "Commercial HVAC diagnostics, repair, maintenance, and rooftop-unit service across Chesapeake and South Hampton Roads.",
    content: {
      eyebrow: "Commercial HVAC Service & Maintenance",
      title: <><strong>Commercial HVAC Problems?</strong><span>We’ll Find the Cause.</span></>,
      lead: "Comfort problems can interrupt the day for customers, employees, and tenants. Ferguson & Sons provides commercial HVAC diagnostics, repair, maintenance, and rooftop-unit service for local businesses across South Hampton Roads.",
      heroImage: commercialHero,
      heroAlt: "Ferguson & Sons technician diagnosing a commercial rooftop HVAC unit",
      imageBadge: "Test the System First",
      problemsHeading: <>When Your Business Needs <em>Dependable HVAC Support</em></>,
      problemsIntro: "We troubleshoot commercial system problems and explain the practical service options before work moves forward.",
      problems: [
        { label: "Business Space Not Comfortable", icon: "building" },
        { label: "Rooftop Unit Not Performing", icon: "home" },
        { label: "Uneven Temperatures", icon: "thermostat" },
        { label: "Weak or Unbalanced Airflow", icon: "airflow" },
        { label: "Recurring System Disruptions", icon: "alert" },
        { label: "Commercial Maintenance Due", icon: "clock" },
      ],
      approachTitle: <>Diagnose the Equipment.<span>Recommend the Right Service.</span></>,
      approachIntro: "Commercial systems deserve the same careful, service-first approach. We evaluate the equipment, identify the issue, and explain the repair or maintenance work that makes sense.",
      steps: [
        { title: "Inspect & Diagnose", description: "We evaluate the commercial HVAC equipment and test the areas relevant to the reported performance problem.", icon: "diagnosis" },
        { title: "Explain the Findings", description: "We provide a clear explanation of what we found and the available service or repair options.", icon: "family" },
        { title: "Service the Right Problem", description: "We complete appropriate repair or maintenance work and discuss replacement only when it is the sensible next step.", icon: "tools" },
      ],
      realServiceEyebrow: "Real Commercial HVAC Work",
      realServiceTitle: <>Hands-On Service for<br />Commercial Equipment</>,
      realServiceDescription: "From rooftop-unit diagnostics to routine commercial maintenance, Ferguson & Sons brings practical troubleshooting and direct communication to each service visit.",
      realServicePoints: ["Commercial HVAC Diagnostics", "Rooftop-Unit Service", "Commercial Repair & Maintenance"],
      realServiceImage: commercialSecondary,
      realServiceAlt: "Commercial rooftop HVAC unit prepared for filter replacement and maintenance",
      supportEyebrow: "Commercial HVAC Capability",
      supportTitle: "Service, Repair, Diagnostics, and Maintenance.",
      supportDescription: "Ferguson & Sons supports commercial HVAC systems with hands-on diagnostics, repair, preventative maintenance, and rooftop-unit service.",
      supportItems: [
        { label: "Commercial Diagnostics", icon: "diagnosis" },
        { label: "Commercial HVAC Repair", icon: "tools" },
        { label: "Commercial Maintenance", icon: "gear" },
        { label: "Rooftop-Unit Service", icon: "building" },
      ],
      relatedServices: [
        { title: "HVAC Maintenance / Tune-Ups", description: "Preventative service and cleaning for residential and commercial systems.", href: "/services/hvac-maintenance/", icon: "gear" },
        { title: "HVAC Component Repair", description: "Diagnosis and service for specific HVAC operating components.", href: "/services/hvac-component-repair/", icon: "tools" },
        { title: "HVAC Replacement / Installation", description: "System changeouts and installation when replacement is the sensible option.", href: "/services/hvac-replacement-installation/", icon: "home" },
        { title: "Indoor Air Quality", description: "Available filters and other indoor air quality products for comfort support.", href: "/services/indoor-air-quality/", icon: "air-quality" },
      ],
      serviceAreaEyebrow: "Local Commercial HVAC Service",
      serviceAreaTitle: "Serving South Hampton Roads Businesses",
      serviceAreaDescription,
      finalCtaHeading: "Need Commercial HVAC Service?",
      finalCtaDescription: "Dependable diagnostics, repair, and maintenance for local businesses across Ferguson & Sons’ regular service area.",
    },
  },
  "hvac-replacement-installation": {
    title: "HVAC Replacement & Installation | Ferguson & Sons",
    description: "Straightforward HVAC replacement, system changeouts, and installation across Chesapeake and South Hampton Roads.",
    content: {
      eyebrow: "HVAC Replacement / Changeouts / Installation",
      title: <><strong>When Replacement Makes Sense,</strong><span>We’ll Explain the Next Step.</span></>,
      lead: "Replacement should not be the automatic answer to every HVAC problem. When repair is no longer the sensible option, Ferguson & Sons provides clear recommendations, system changeouts, and professional HVAC installation.",
      heroImage: replacementHero,
      heroAlt: "Two residential outdoor HVAC systems installed beside a home",
      imageBadgeEyebrow: "Straightforward Options",
      imageBadge: "Replace When It Makes Sense",
      problemsHeading: <>When It May Be Time to <em>Discuss Replacement</em></>,
      problemsIntro: "We evaluate the existing equipment and the repair options before recommending a system changeout.",
      problems: [
        { label: "Repair Is No Longer Practical", icon: "tools" },
        { label: "Repeated Major System Problems", icon: "alert" },
        { label: "System Changeout Is Planned", icon: "home" },
        { label: "Existing Equipment Needs Replacement", icon: "furnace" },
        { label: "New HVAC Installation Needed", icon: "gear" },
        { label: "Clear Options Are Needed", icon: "family" },
      ],
      approachTitle: <>Assess First.<span>Install With a Clear Plan.</span></>,
      approachIntro: "Our service-first philosophy still applies when replacement is being considered. We look at the existing system, explain why replacement may be appropriate, and outline the next step clearly.",
      approachCta: "Request a Replacement Quote",
      steps: [
        { title: "Evaluate the Existing System", description: "We review the equipment and the practical repair or replacement considerations before recommending a changeout.", icon: "diagnosis" },
        { title: "Explain the Recommendation", description: "We walk through the findings and provide a straightforward explanation of the proposed installation work.", icon: "family" },
        { title: "Complete the Changeout", description: "When replacement is selected, we complete the HVAC changeout and installation with careful attention to the system setup.", icon: "tools" },
      ],
      realServiceEyebrow: "Real HVAC Installation",
      realServiceTitle: <>Replacement Starts With<br />an Honest Recommendation</>,
      realServiceDescription: "Ferguson & Sons offers system replacement and installation without treating new equipment as the default answer. The goal is to choose the sensible path for the actual system condition.",
      realServicePoints: ["System Changeouts", "HVAC Installation", "Repair Considered First"],
      realServiceImage: replacementSecondary,
      realServiceAlt: "New residential outdoor HVAC system installed beside a brick home",
      supportEyebrow: "Service Before Replacement",
      supportTitle: "A New System Is One Option — Not Every Answer.",
      supportDescription: "Careful diagnosis helps separate repairable problems from situations where replacement is the more practical next step.",
      supportItems: [
        { label: "Existing-System Review", icon: "diagnosis" },
        { label: "Repair Considered First", icon: "tools" },
        { label: "Clear Recommendation", icon: "family" },
        { label: "Changeout & Installation", icon: "home" },
      ],
      relatedServices: [
        { title: "A/C Repair & Diagnosis", description: "Troubleshooting and repair before replacement is considered.", href: "/services/ac-repair/", icon: "snowflake" },
        { title: "Heat Pump Service / Repair", description: "Heat pump diagnosis, repair, service, and maintenance.", href: "/services/heat-pump-repair/", icon: "heat-pump" },
        { title: "Furnace Service / Repair", description: "Furnace diagnosis and repair with a service-first approach.", href: "/services/furnace-repair/", icon: "furnace" },
        { title: "HVAC Maintenance / Tune-Ups", description: "Routine service and cleaning to support reliable system operation.", href: "/services/hvac-maintenance/", icon: "gear" },
      ],
      serviceAreaEyebrow: "Local HVAC Installation",
      serviceAreaTitle: "Serving South Hampton Roads",
      serviceAreaDescription,
      finalCtaHeading: "Considering HVAC Replacement?",
      finalCtaDescription: "Get a straightforward evaluation and clear next-step recommendation from a local, service-first HVAC team.",
    },
  },
  "hvac-component-repair": {
    title: "HVAC Component Repair & Replacement | Ferguson & Sons",
    description: "Diagnosis, repair, and replacement of capacitors, compressors, condenser fan motors, contactors, and related HVAC components.",
    content: {
      eyebrow: "HVAC Component Repair / Replacement",
      title: <><strong>One Failed Component?</strong><span>Let’s Find the Right Fix.</span></>,
      lead: "A system problem does not always mean the entire HVAC unit needs replacement. Ferguson & Sons diagnoses specific operating and electrical components, then repairs or replaces the affected part when that is the sensible solution.",
      heroImage: componentHero,
      heroAlt: "Residential outdoor HVAC unit connected to diagnostic gauges and service tools",
      imageBadge: "Isolate the Failed Part",
      problemsHeading: <>When the Problem May Be <em>Inside the System</em></>,
      problemsIntro: "Careful testing helps identify whether a specific component is behind the system problem.",
      problems: [
        { label: "System Will Not Start", icon: "power" },
        { label: "Condenser Fan Not Operating", icon: "fan" },
        { label: "Irregular System Cycling", icon: "gauge" },
        { label: "Compressor-Related Problem", icon: "gear" },
        { label: "Contactor or Control Issue", icon: "zap" },
        { label: "Unexpected Performance Change", icon: "alert" },
      ],
      approachTitle: <>Test the Components.<span>Repair the Actual Problem.</span></>,
      approachIntro: "We do not replace parts by guesswork. We test the relevant components, explain the findings, and recommend targeted repair or replacement based on the diagnosis.",
      steps: [
        { title: "Test the System", description: "We inspect the equipment and test the components connected to the reported operating problem.", icon: "diagnosis" },
        { title: "Identify the Failed Part", description: "We isolate the component or related issue and explain what it is doing to system operation.", icon: "gear" },
        { title: "Repair or Replace the Component", description: "When appropriate, we repair or replace the affected part instead of recommending an entire system replacement.", icon: "tools" },
      ],
      realServiceEyebrow: "Targeted HVAC Repair",
      realServiceTitle: <>Component Work Begins With<br />Accurate Diagnosis</>,
      realServiceDescription: "Ferguson & Sons works on the operating and electrical components that keep HVAC equipment running. The repair starts by understanding which part failed and why the system is not performing properly.",
      realServicePoints: ["Diagnosis Before Replacement", "Targeted Component Service", "Repair-First Expertise"],
      realServiceImage: componentSecondary,
      realServiceAlt: "Electrical contactors and wiring inside an outdoor HVAC unit",
      supportEyebrow: "Component Service",
      supportTitle: "Repair the Part — Not Automatically the Whole System.",
      supportDescription: "Confirmed component work includes capacitors, compressors, condenser fan motors, contactors, and related HVAC electrical and operating parts.",
      supportItems: [
        { label: "Capacitors", icon: "zap" },
        { label: "Compressors", icon: "gear" },
        { label: "Condenser Fan Motors", icon: "fan" },
        { label: "Contactors & Related Parts", icon: "tools" },
      ],
      relatedServices: [
        { title: "A/C Repair & Diagnosis", description: "No-cooling troubleshooting and repair for residential and commercial systems.", href: "/services/ac-repair/", icon: "snowflake" },
        { title: "Heat Pump Service / Repair", description: "Diagnosis and repair for heat pump heating and cooling problems.", href: "/services/heat-pump-repair/", icon: "heat-pump" },
        { title: "Furnace Service / Repair", description: "Straightforward furnace troubleshooting, service, and repair.", href: "/services/furnace-repair/", icon: "furnace" },
        { title: "HVAC Replacement / Installation", description: "Replacement and changeouts when repair is no longer sensible.", href: "/services/hvac-replacement-installation/", icon: "home" },
      ],
      serviceAreaEyebrow: "Local HVAC Component Repair",
      serviceAreaTitle: "Serving South Hampton Roads",
      serviceAreaDescription,
      finalCtaHeading: "Suspect an HVAC Component Problem?",
      finalCtaDescription: "Get careful diagnosis and a practical repair recommendation from Ferguson & Sons.",
    },
  },
  "ductless-mini-splits": {
    title: "Ductless Mini-Split Installation & Service | Ferguson & Sons",
    description: "Ductless mini-split installation, diagnostics, repair, service, and maintenance across South Hampton Roads.",
    content: {
      eyebrow: "Ductless Mini-Split Installation & Service",
      title: <><strong>Need Mini-Split Service?</strong><span>We’ll Check the System.</span></>,
      lead: "Ferguson & Sons provides ductless mini-split installation, service, repair, and maintenance. Whether an existing system needs attention or a new ductless installation is being considered, we start with the actual comfort need.",
      heroImage: miniSplitHero,
      heroAlt: "Ferguson & Sons technician installing a ductless mini-split indoor unit",
      imageBadgeEyebrow: "Ductless Service",
      imageBadge: "Install, Service, or Repair",
      problemsHeading: <>When Your Mini-Split Needs <em>Professional Service</em></>,
      problemsIntro: "We inspect the ductless equipment and recommend service, repair, maintenance, or installation based on what the system needs.",
      problems: [
        { label: "Unit Not Heating or Cooling", icon: "thermostat" },
        { label: "Weak or Uneven Airflow", icon: "airflow" },
        { label: "Startup or Control Problem", icon: "power" },
        { label: "Cleaning or Maintenance Needed", icon: "gear" },
        { label: "Existing Mini-Split Needs Repair", icon: "tools" },
        { label: "New Ductless Installation", icon: "home" },
      ],
      approachTitle: <>Understand the Need.<span>Recommend the Right Ductless Service.</span></>,
      approachIntro: "Mini-split work can involve installation, troubleshooting, repair, or maintenance. We identify the actual need and explain the service path clearly.",
      approachCta: "Request Mini-Split Service",
      steps: [
        { title: "Assess the System or Space", description: "We review the existing mini-split problem or the need for a new ductless installation.", icon: "diagnosis" },
        { title: "Explain the Options", description: "We discuss the appropriate service, repair, maintenance, or installation path without inventing product features.", icon: "family" },
        { title: "Complete the Ductless Work", description: "We perform the agreed mini-split service or installation with a practical, system-focused approach.", icon: "tools" },
      ],
      realServiceEyebrow: "Real Ductless HVAC Work",
      realServiceTitle: <>Ductless Comfort Requires<br />Careful System Service</>,
      realServiceDescription: "Mini-splits combine indoor and outdoor equipment that must work together. Ferguson & Sons services the system as a whole and explains what is needed before work proceeds.",
      realServicePoints: ["Mini-Split Installation", "Mini-Split Service & Repair", "Mini-Split Maintenance"],
      realServiceImage: miniSplitSecondary,
      realServiceAlt: "Open ductless mini-split indoor unit during cleaning and service",
      supportEyebrow: "Ductless Mini-Split Scope",
      supportTitle: "Installation, Repair, Service, and Maintenance.",
      supportDescription: "Ferguson & Sons supports ductless mini-splits from new installation through ongoing service, repair, and maintenance.",
      supportItems: [
        { label: "Mini-Split Installation", icon: "home" },
        { label: "Mini-Split Diagnostics", icon: "diagnosis" },
        { label: "Mini-Split Repair", icon: "tools" },
        { label: "Mini-Split Maintenance", icon: "gear" },
      ],
      relatedServices: [
        { title: "HVAC Replacement / Installation", description: "System changeouts and HVAC installation when replacement is appropriate.", href: "/services/hvac-replacement-installation/", icon: "home" },
        { title: "HVAC Maintenance / Tune-Ups", description: "Professional tune-ups, cleaning, and preventative service.", href: "/services/hvac-maintenance/", icon: "gear" },
        { title: "Thermostat Installation", description: "Thermostat replacement, installation, and system-control troubleshooting.", href: "/services/thermostats/", icon: "thermostat" },
        { title: "Indoor Air Quality", description: "Filters, UV lights, humidifiers, and dehumidifiers for comfort support.", href: "/services/indoor-air-quality/", icon: "air-quality" },
      ],
      serviceAreaEyebrow: "Local Mini-Split Service",
      serviceAreaTitle: "Serving South Hampton Roads",
      serviceAreaDescription,
      finalCtaHeading: "Need Mini-Split Installation or Service?",
      finalCtaDescription: "Local ductless mini-split installation, repair, service, and maintenance from Ferguson & Sons.",
    },
  },
  thermostats: {
    title: "Thermostat Replacement & Installation | Ferguson & Sons",
    description: "Thermostat replacement, installation, and HVAC system-control troubleshooting across South Hampton Roads.",
    content: {
      eyebrow: "Thermostat Replacement / Installation",
      title: <><strong>Thermostat Not Responding?</strong><span>We’ll Check the Controls.</span></>,
      lead: "A thermostat or system-control problem can affect how the HVAC equipment responds. Ferguson & Sons provides thermostat troubleshooting, replacement, and installation without making unsupported promises about brands or smart-home features.",
      heroImage: thermostatHero,
      heroAlt: "Wall-mounted thermostat displaying heating settings",
      imageBadge: "Check the Controls First",
      problemsHeading: <>When the Thermostat Is Not <em>Controlling Comfort</em></>,
      problemsIntro: "We troubleshoot the thermostat and related system-control response before recommending replacement.",
      problems: [
        { label: "Thermostat Not Responding", icon: "power" },
        { label: "System Does Not Follow Settings", icon: "thermostat" },
        { label: "Heating or Cooling Will Not Start", icon: "snowflake" },
        { label: "Control Response Is Inconsistent", icon: "gauge" },
        { label: "Thermostat Replacement Needed", icon: "tools" },
        { label: "New Thermostat Installation", icon: "home" },
      ],
      approachTitle: <>Troubleshoot the Controls.<span>Set Up the Right Next Step.</span></>,
      approachIntro: "We look at the thermostat and how the HVAC system responds, explain the findings, and recommend troubleshooting, replacement, or installation based on the actual control issue.",
      approachCta: "Request Thermostat Service",
      steps: [
        { title: "Check the Thermostat", description: "We inspect the thermostat setup and the system response connected to the reported problem.", icon: "diagnosis" },
        { title: "Explain the Control Issue", description: "We explain whether the concern points to the thermostat, its setup, or another HVAC system-control issue.", icon: "family" },
        { title: "Replace or Install When Needed", description: "When thermostat replacement or installation is appropriate, we complete the work and verify system response.", icon: "tools" },
      ],
      realServiceEyebrow: "Real Thermostat Service",
      realServiceTitle: <>Control Problems Start With<br />Checking the Connections</>,
      realServiceDescription: "Thermostat service is more than changing the device on the wall. Ferguson & Sons evaluates the control concern and how it relates to HVAC system operation.",
      realServicePoints: ["Thermostat Troubleshooting", "Thermostat Replacement", "Thermostat Installation"],
      realServiceImage: thermostatSecondary,
      realServiceAlt: "Thermostat wiring and wall plate exposed during replacement service",
      supportEyebrow: "System Controls",
      supportTitle: "Clear Thermostat Service Without Unsupported Product Claims.",
      supportDescription: "Ferguson & Sons provides thermostat replacement, installation, and related system-control troubleshooting based on the equipment and the issue found.",
      supportItems: [
        { label: "Control Troubleshooting", icon: "diagnosis" },
        { label: "Thermostat Replacement", icon: "thermostat" },
        { label: "Thermostat Installation", icon: "tools" },
        { label: "System Response Check", icon: "gauge" },
      ],
      relatedServices: [
        { title: "A/C Repair & Diagnosis", description: "Cooling-system troubleshooting when the problem extends beyond the thermostat.", href: "/services/ac-repair/", icon: "snowflake" },
        { title: "Heat Pump Service / Repair", description: "Heat pump diagnosis, service, repair, and maintenance.", href: "/services/heat-pump-repair/", icon: "heat-pump" },
        { title: "Furnace Service / Repair", description: "Furnace diagnostics and repair for heating problems.", href: "/services/furnace-repair/", icon: "furnace" },
        { title: "HVAC Maintenance / Tune-Ups", description: "Routine service that includes attention to system operation and controls.", href: "/services/hvac-maintenance/", icon: "gear" },
      ],
      serviceAreaEyebrow: "Local Thermostat Service",
      serviceAreaTitle: "Serving South Hampton Roads",
      serviceAreaDescription,
      finalCtaHeading: "Need Thermostat Service or Installation?",
      finalCtaDescription: "Straightforward thermostat troubleshooting, replacement, and installation from Ferguson & Sons.",
    },
  },
  "indoor-air-quality": {
    title: "Indoor Air Quality Products & Solutions | Ferguson & Sons",
    description: "HVAC filters, UV lights, humidifiers, and dehumidifiers for indoor comfort and air-quality support.",
    content: {
      eyebrow: "Indoor Air Quality",
      title: <><strong>Looking for Better Indoor</strong><span>Air & Comfort Support?</span></>,
      lead: "Ferguson & Sons offers practical indoor air quality product options centered on comfort, air-quality support, and HVAC system care. Available categories include filters, UV lights, humidifiers, and dehumidifiers.",
      heroImage: airQualityHero,
      heroAlt: "Technician checking supply-air temperature at an indoor HVAC vent",
      imageBadgeEyebrow: "Comfort Support",
      imageBadge: "Review the Indoor System",
      problemsHeading: <>Indoor Air Quality Options for <em>Comfort and System Care</em></>,
      problemsIntro: "We help customers understand the available HVAC-related product categories without making unsupported health or medical claims.",
      problems: [
        { label: "Filter Options", icon: "air-quality" },
        { label: "UV Light Options", icon: "zap" },
        { label: "Humidity Support", icon: "airflow" },
        { label: "Dehumidification Options", icon: "snowflake" },
        { label: "Indoor Comfort Concerns", icon: "thermostat" },
        { label: "HVAC System Care", icon: "gear" },
      ],
      approachTitle: <>Understand the Concern.<span>Discuss the Available Options.</span></>,
      approachIntro: "Indoor air quality needs vary by building and HVAC system. We discuss the comfort or system-care concern and explain which available product category may be relevant.",
      approachCta: "Ask About Indoor Air Quality",
      steps: [
        { title: "Review the Comfort Concern", description: "We listen to the indoor comfort or air-quality concern and consider how it relates to the HVAC system.", icon: "diagnosis" },
        { title: "Explain Available Products", description: "We discuss available filters, UV lights, humidifiers, or dehumidifiers without inventing health benefits or product features.", icon: "family" },
        { title: "Recommend a Practical Option", description: "When an indoor air quality product is appropriate, we explain the next step in clear, practical terms.", icon: "tools" },
      ],
      realServiceEyebrow: "Indoor Comfort & Air Support",
      realServiceTitle: <>Indoor Air Quality Is Part of<br />the HVAC System Conversation</>,
      realServiceDescription: "Air movement, filtration, humidity, and equipment condition can all shape indoor comfort. Ferguson & Sons keeps the conversation grounded in the available HVAC-related solutions.",
      realServicePoints: ["Comfort-Focused Guidance", "Available IAQ Products", "No Unsupported Medical Claims"],
      realServiceImage: airQualitySecondary,
      realServiceAlt: "Wall-mounted ductless HVAC unit supporting indoor airflow and comfort",
      supportEyebrow: "Available IAQ Products",
      supportTitle: "Four Practical Product Categories.",
      supportDescription: "The confirmed Ferguson & Sons indoor air quality offering includes filters, UV lights, humidifiers, and dehumidifiers.",
      supportItems: [
        { label: "Filters", icon: "air-quality" },
        { label: "UV Lights", icon: "zap" },
        { label: "Humidifiers", icon: "airflow" },
        { label: "Dehumidifiers", icon: "snowflake" },
      ],
      relatedServices: [
        { title: "HVAC Maintenance / Tune-Ups", description: "Cleaning, filter-related maintenance, and preventative system service.", href: "/services/hvac-maintenance/", icon: "gear" },
        { title: "Ductless Mini-Splits", description: "Ductless mini-split installation, service, repair, and maintenance.", href: "/services/ductless-mini-splits/", icon: "airflow" },
        { title: "Thermostat Installation", description: "Thermostat replacement, installation, and system-control troubleshooting.", href: "/services/thermostats/", icon: "thermostat" },
        { title: "A/C Repair & Diagnosis", description: "Cooling-system troubleshooting and repair when comfort problems persist.", href: "/services/ac-repair/", icon: "snowflake" },
      ],
      serviceAreaEyebrow: "Local Indoor Air Quality Support",
      serviceAreaTitle: "Serving South Hampton Roads",
      serviceAreaDescription,
      finalCtaHeading: "Want to Discuss Indoor Air Quality Options?",
      finalCtaDescription: "Ask Ferguson & Sons about filters, UV lights, humidifiers, and dehumidifiers for your HVAC system.",
    },
  },
  "heat-pump-repair": {
    title: "Heat Pump Service & Repair | Ferguson & Sons",
    description: "Heat pump diagnostics, service, repair, and maintenance across Chesapeake and South Hampton Roads.",
    content: {
      eyebrow: "Heat Pump Service / Repair",
      title: <><strong>Heat Pump Not Keeping Up?</strong><span>We’ll Diagnose the Problem.</span></>,
      lead: "Heat pumps support both heating and cooling, so a performance problem can affect comfort in more than one season. Ferguson & Sons provides heat pump diagnostics, service, repair, and maintenance with a service-first approach.",
      heroImage: heatPumpHero,
      heroAlt: "Residential outdoor heat pump equipment during service",
      imageBadge: "Find the Cause First",
      problemsHeading: <>When Your Heat Pump Is Not <em>Keeping You Comfortable</em></>,
      problemsIntro: "We troubleshoot heating and cooling performance before recommending repair, maintenance, or replacement.",
      problems: [
        { label: "Not Heating Properly", icon: "furnace" },
        { label: "Not Cooling Properly", icon: "snowflake" },
        { label: "Weak or Uneven Airflow", icon: "airflow" },
        { label: "Cycling On and Off", icon: "power" },
        { label: "Control or Thermostat Concern", icon: "thermostat" },
        { label: "Seasonal Service Needed", icon: "clock" },
      ],
      approachTitle: <>Diagnose the Heat Pump.<span>Recommend the Sensible Next Step.</span></>,
      approachIntro: "We evaluate heat pump operation, explain the findings, and focus on service or repair when that is the practical solution. Replacement is discussed only when appropriate.",
      steps: [
        { title: "Inspect & Diagnose", description: "We evaluate the heat pump and test relevant areas to identify the source of the heating or cooling problem.", icon: "diagnosis" },
        { title: "Explain the Findings", description: "We explain what we found and how it affects heat pump operation in clear, practical language.", icon: "family" },
        { title: "Service, Repair, or Recommend", description: "We complete sensible service or repair work and discuss replacement only when the equipment condition supports that recommendation.", icon: "tools" },
      ],
      realServiceEyebrow: "Real Heat Pump Service",
      realServiceTitle: <>Heating and Cooling Problems<br />Need Careful Troubleshooting</>,
      realServiceDescription: "Because heat pumps work across seasons, diagnosis should consider the system’s heating, cooling, controls, and maintenance condition before deciding on the next step.",
      realServicePoints: ["Heat Pump Diagnostics", "Heat Pump Service & Repair", "Heat Pump Maintenance"],
      realServiceImage: heatPumpSecondary,
      realServiceAlt: "Technician checking a ductless heat pump indoor unit with a temperature tool",
      supportEyebrow: "Heat Pump Service Scope",
      supportTitle: "Diagnostics, Service, Repair, and Maintenance.",
      supportDescription: "Ferguson & Sons supports heat pump systems with careful troubleshooting, practical repair, and preventative maintenance.",
      supportItems: [
        { label: "Heat Pump Diagnostics", icon: "diagnosis" },
        { label: "Heating Performance", icon: "furnace" },
        { label: "Cooling Performance", icon: "snowflake" },
        { label: "Maintenance & Repair", icon: "tools" },
      ],
      relatedServices: [
        { title: "HVAC Maintenance / Tune-Ups", description: "Preventative tune-ups and cleaning for reliable system operation.", href: "/services/hvac-maintenance/", icon: "gear" },
        { title: "HVAC Component Repair", description: "Diagnosis and targeted service for specific HVAC components.", href: "/services/hvac-component-repair/", icon: "tools" },
        { title: "HVAC Replacement / Installation", description: "Heat pump or HVAC replacement when repair is no longer sensible.", href: "/services/hvac-replacement-installation/", icon: "home" },
        { title: "Thermostat Installation", description: "Thermostat replacement and troubleshooting for related control concerns.", href: "/services/thermostats/", icon: "thermostat" },
      ],
      serviceAreaEyebrow: "Local Heat Pump Service",
      serviceAreaTitle: "Serving South Hampton Roads",
      serviceAreaDescription,
      finalCtaHeading: "Heat Pump Not Performing Properly?",
      finalCtaDescription: "Get straightforward heat pump diagnosis, service, and repair from Ferguson & Sons.",
    },
  },
  "furnace-repair": {
    title: "Furnace Service & Repair | Ferguson & Sons",
    description: "Furnace diagnostics, service, repair, and maintenance across Chesapeake and South Hampton Roads.",
    content: {
      eyebrow: "Furnace Service / Repair",
      title: <><strong>Furnace Not Heating?</strong><span>We’ll Find the Problem.</span></>,
      lead: "When a furnace is not keeping the space comfortable, the right first step is careful troubleshooting. Ferguson & Sons provides furnace diagnostics, service, repair, and maintenance without treating replacement as the automatic answer.",
      heroImage: furnaceHero,
      heroAlt: "Residential furnace and indoor HVAC equipment",
      imageBadge: "Diagnose the Heating Issue",
      problemsHeading: <>When Your Furnace Is Not <em>Heating Properly</em></>,
      problemsIntro: "We evaluate the heating problem and explain the practical service or repair options before work moves forward.",
      problems: [
        { label: "Furnace Not Producing Heat", icon: "furnace" },
        { label: "Heating Is Not Keeping Up", icon: "thermostat" },
        { label: "Weak or Uneven Airflow", icon: "airflow" },
        { label: "System Cycling Frequently", icon: "power" },
        { label: "Thermostat or Control Concern", icon: "gauge" },
        { label: "Furnace Maintenance Needed", icon: "clock" },
      ],
      approachTitle: <>Diagnose the Furnace.<span>Recommend the Right Next Step.</span></>,
      approachIntro: "We inspect the furnace, identify the reason for the heating problem, and explain the findings before recommending service, repair, maintenance, or replacement.",
      steps: [
        { title: "Inspect & Diagnose", description: "We evaluate furnace operation and the areas relevant to the reported heating or airflow problem.", icon: "diagnosis" },
        { title: "Explain the Findings", description: "We explain what we found, how it affects heating performance, and the available options.", icon: "family" },
        { title: "Service or Repair", description: "We focus on practical furnace service or repair and discuss replacement only when it is the sensible next step.", icon: "tools" },
      ],
      realServiceEyebrow: "Real Furnace Service",
      realServiceTitle: <>Heating Problems Require<br />Accurate System Checks</>,
      realServiceDescription: "Furnace issues can involve system operation, airflow, controls, or maintenance condition. Ferguson & Sons approaches each call by finding the actual cause before recommending work.",
      realServicePoints: ["Furnace Diagnostics", "Furnace Service & Repair", "Furnace Maintenance"],
      realServiceImage: furnaceSecondary,
      realServiceAlt: "Technician measuring supply-air temperature during furnace service",
      supportEyebrow: "Furnace Service Scope",
      supportTitle: "Straightforward Heating Service and Repair.",
      supportDescription: "Ferguson & Sons provides confirmed furnace diagnostics, service, repair, and maintenance with replacement considered only when appropriate.",
      supportItems: [
        { label: "Furnace Diagnostics", icon: "diagnosis" },
        { label: "Heating Troubleshooting", icon: "thermostat" },
        { label: "Furnace Repair", icon: "tools" },
        { label: "Furnace Maintenance", icon: "gear" },
      ],
      relatedServices: [
        { title: "HVAC Maintenance / Tune-Ups", description: "Preventative maintenance and seasonal service for HVAC equipment.", href: "/services/hvac-maintenance/", icon: "gear" },
        { title: "HVAC Component Repair", description: "Targeted service for specific HVAC operating components.", href: "/services/hvac-component-repair/", icon: "tools" },
        { title: "HVAC Replacement / Installation", description: "System replacement when repair is no longer the sensible choice.", href: "/services/hvac-replacement-installation/", icon: "home" },
        { title: "Thermostat Installation", description: "Thermostat replacement and related system-control troubleshooting.", href: "/services/thermostats/", icon: "thermostat" },
      ],
      serviceAreaEyebrow: "Local Furnace Service",
      serviceAreaTitle: "Serving South Hampton Roads",
      serviceAreaDescription,
      finalCtaHeading: "Furnace Not Heating Properly?",
      finalCtaDescription: "Get careful furnace diagnosis, service, and repair from a local Chesapeake HVAC team.",
    },
  },
};

export function generateStaticParams() {
  return Object.keys(servicePages).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const page = servicePages[slug];

  if (!page) return {};

  return createPageMetadata({
    title: page.title,
    description: page.description,
    path: `/services/${slug}/`,
  });
}

export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const page = servicePages[slug];

  if (!page) notFound();

  return <ServiceDetailPage content={page.content} />;
}
